#!/bin/bash

pkill -f "cava -p ~/.config/cava/config_waybar"

# s/0/ / -> меняем 0 (тишину) на маленький значок " ", чтобы видеть, что столбики есть
cava -p ~/.config/cava/config_waybar | sed -u 's/;//g;s/0/ /g;s/1/▂/g;s/2/▃/g;s/3/▄/g;s/4/▅/g;s/5/▆/g;s/6/▇/g;s/7/█/g;'
