#!/bin/bash

WALL_DIR="$HOME/Pictures/Wallpapers"

# --- ФУНКЦИЯ ПОИСКА И СОРТИРОВКИ ---
# Мы ищем файлы, а потом сортируем их так:
# 1. Строки, начинающиеся на "S/", получают высший приоритет
# 2. Потом "A/", "B/", "C/", "D/"
# 3. Всё остальное
get_list() {
    find "$WALL_DIR" -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.webp" \) | \
    sed "s|$WALL_DIR/||" | \
    awk '{
        # Присваиваем вес каждой папке
        if ($0 ~ /^S\//)      print "1 " $0;
        else if ($0 ~ /^A\//) print "2 " $0;
        else if ($0 ~ /^B\//) print "3 " $0;
        else if ($0 ~ /^C\//) print "4 " $0;
        else if ($0 ~ /^D\//) print "5 " $0;
        else                  print "9 " $0;
    }' | \
    sort -k1,1n -k2 | \
    cut -d ' ' -f2- # Убираем цифру сортировки перед показом
}

# --- ЗАПУСК МЕНЮ ---
# Флаг -i делает поиск нечувствительным к регистру (s найдет S)
SELECTED=$(get_list | rofi -dmenu -p "Choose Wallpaper" -i -theme ~/.config/rofi/style.rasi)

if [ -z "$SELECTED" ]; then
    exit 0
fi

setwall "$WALL_DIR/$SELECTED"
